name: Publish to NPM

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js 12.x
      uses: actions/setup-node@v3
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Install, Build and Test 🔧
      run: |
        yarn install
        yarn run build --if-present
        yarn test
      env:
        CI: true
    - name: Publish
      run: Publish package on NPM 📦
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
